version: "3"
services:
  database:
    image: postgres:15.1
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  service:
    build: ./
    container_name: service
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres?currentSchema=public
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - database

volumes:
  pgdata: