server:
  port: 8080
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=uzers
    #    url: jdbc:postgresql://db:5432/postgres?currentSchema=uzers
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    liquibase-schema: uzers
    enabled: true